name: Sync data to Hugging Face bucket

on:
  workflow_run:
    workflows: ["Update Data Daily"]
    types:
      - completed

  workflow_dispatch:

jobs:
  sync-data:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv (with uvx)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync data to HF bucket
        run: |
          uvx hf sync ./data \
            hf://buckets/e-zaline/power-plant-tracker-storage \
            --token $HF_TOKEN